#!/bin/sh

set -e

testdir=$(mktemp -d)
trap "rm -rf ${testdir}" 0 INT QUIT ABRT PIPE TERM
cd ${testdir}

cat <<EOF > test.ml
open Base64
let r = Base64.str_decode (Base64.str_encode "Hello world!")
let _ = Printf.printf "%s" r
EOF

if [ -x '/usr/bin/ocamlopt' ]
then
    ocamlfind ocamlopt -o native-code-test -I `ocamlfind query extlib` extLib.cmxa test.ml

    echo "build: OK"

    [ -x native-code-test ]
    ./native-code-test 2> /dev/null | grep -q "Hello world!"

    echo "run: OK"
else
    echo "skip native-code test since ocamlopt is not available"
fi
