#!/bin/sh

set -e

testdir=$(mktemp -d)
trap "rm -rf ${testdir}" 0 INT QUIT ABRT PIPE TERM
cd ${testdir}

cat <<EOF > test.ml
open ExtString
module S = String
let _ = assert (S.starts_with "foo" "f")
EOF

if [ -x '/usr/bin/ocamlopt' ]
then
    ocamlfind ocamlopt -o native-code-test -I `ocamlfind query extlib` extLib.cmxa test.ml

    echo "build: OK"

    [ -x native-code-test ]
    ./native-code-test

    echo "run: OK"
else
    echo "skip native-code test since ocamlopt is not available"
fi
